#   Copyright 2024 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
version: '3.1'
secrets:
  host_certificate_file:
    file: ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}
services:
  platform-auth:
    build:
      context: ${PLATFORM_REPO_ROOT}
      target: develop_build
      secrets:
        - host_certificate_file
    volumes:
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    environment:
      - LOG_LEVEL=DEBUG
      - ITA_WEB_PROTOCOL=http
      - ITA_WEB_HOST=ita-web-server
      - ITA_WEB_PORT=80
      - ITA_API_PROTOCOL=http
      - ITA_API_HOST=ita-api-organization
      - ITA_API_PORT=8000
      - ITA_API_ADMIN_PROTOCOL=http
      - ITA_API_ADMIN_HOST=ita-api-admin
      - ITA_API_ADMIN_PORT=8079
      - ITA_API_OASE_RECEIVER_PROTOCOL=http
      - ITA_API_OASE_RECEIVER_HOST=ita-api-oase-receiver
      - ITA_API_OASE_RECEIVER_PORT=8000
      - EPOCH_SERVER_HOST=epoch-server
      - EPOCH_SERVER_PROTOCOL=http
      - EPOCH_SERVER_PORT=8000
      - HTTP_PROXY=${HTTP_PROXY}
      - http_proxy=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY},epoch-server,epoch-agent,keycloak,platform-auth,platform-api,platform-web,ita-web-server,ita-api-organization,ita-api-admin,ita-api-oase-receiver
      - no_proxy=${NO_PROXY},epoch-server,epoch-agent,keycloak,platform-auth,platform-api,platform-web,ita-web-server,ita-api-organization,ita-api-admin,ita-api-oase-receiver
  platform-api:
    build:
      context: ${PLATFORM_REPO_ROOT}
      target: develop_build
      secrets:
        - host_certificate_file
    volumes:
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    environment:
      - LOG_LEVEL=DEBUG
      - ITA_API_ADMIN_PROTOCOL=http
      - ITA_API_ADMIN_HOST=ita-api-admin
      - ITA_API_ADMIN_PORT=8079
      - HTTP_PROXY=${HTTP_PROXY}
      - http_proxy=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY},epoch-server,epoch-agent,keycloak,platform-auth,platform-api,platform-web,ita-web-server,ita-api-organization,ita-api-admin,ita-api-oase-receiver
      - no_proxy=${NO_PROXY},epoch-server,epoch-agent,keycloak,platform-auth,platform-api,platform-web,ita-web-server,ita-api-organization,ita-api-admin,ita-api-oase-receiver

  platform-job:
    build:
      context: ${PLATFORM_REPO_ROOT}
      target: develop_build
      secrets:
        - host_certificate_file
    volumes:
      - ${HOST_CERTIFICATE_FILE:-/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem}:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    environment:
      - LOG_LEVEL=DEBUG
      - HTTP_PROXY=${HTTP_PROXY}
      - http_proxy=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY},epoch-server,epoch-agent,keycloak,platform-auth,platform-api,platform-web,ita-web-server,ita-api-organization,ita-api-admin,ita-api-oase-receiver
      - no_proxy=${NO_PROXY},epoch-server,epoch-agent,keycloak,platform-auth,platform-api,platform-web,ita-web-server,ita-api-organization,ita-api-admin,ita-api-oase-receiver

  platform-web:
    build:
      context: ${PLATFORM_REPO_ROOT}
      target: develop_build
      secrets:
        - host_certificate_file

  platform-db:
    volumes:
      - ${PLATFORM_REPO_ROOT}/platform_root/platform_db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "0.0.0.0:${EXT_PORT_PLATFORM_DB:-3307}:3306"

  platform-migration-1:
    build:
      context: ${PLATFORM_REPO_ROOT}
      secrets:
        - host_certificate_file
    environment:
      - LOG_LEVEL=DEBUG

  platform-migration-2:
    build:
      context: ${PLATFORM_REPO_ROOT}
      target: develop_build
      secrets:
        - host_certificate_file
    environment:
      - LOG_LEVEL=DEBUG

  keycloak:
    build:
      context: ${PLATFORM_REPO_ROOT}
      target: develop_build
      secrets:
        - host_certificate_file
    volumes:
      - /usr/share/pki/ca-trust-source/anchors/UserRootCertificate.crt:/etc/ssl/certs/ca-certificates.crt
    environment:
      - JAVA_OPTS_APPEND=-Xms256m -Xmx256m
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - SSL_CERT_DIR=/etc/ssl/certs
