#   Copyright 2024 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

version: '3.1'
services:
  epoch-server:
    user: 1000:1000
    build:
      dockerfile: ./epoch_root/epoch_server/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - LISTEN_PORT_WEB=8000
      - LISTEN_PORT_API=8001
      - DB_HOST=${EPOCH_DB_HOST:-epoch-db}
      - DB_DATABASE=epoch
      - DB_USER=app_user
      - DB_PASSWORD=password
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=password
      - ENCRYPT_KEY=${ENCRYPT_KEY}
    networks:
      - exastro

  epoch-agent:
    user: 1000:1000
    build:
      dockerfile: ./epoch_root/epoch_agent/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
    networks:
      - exastro

  epoch-db:
    image: mariadb:10.4.8
    healthcheck:
      test: mysqladmin ping --silent && mysql -u root -p$${MYSQL_ROOT_PASSWORD} -e 'select 1;'
      interval: 3s
      retries: 200
    volumes:
      - ../.volumes/epoch-db/data:/var/lib/mysql
      - ../epoch_root/epoch_db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - exastro

  epoch-migration:
    user: 1000:1000
    build:
      dockerfile: ./epoch_root/epoch_migration/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - PYTHONIOENCODING=utf-8
      - DB_HOST=${PLATFORM_DB_HOST:-epoch-db}
      - DB_DATABASE=epoch
      - DB_USER=app_user
      - DB_PASSWORD=password
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=password
      # - TIMEOUT_SECONDS_CONNECT_DB=600
      - ENCRYPT_KEY=${ENCRYPT_KEY}
    networks:
      - exastro
    depends_on:
      epoch-db:
        condition: service_healthy

networks:
  exastro:
    name: "exastro_${NETWORK_ID}"
